name: I2::Profiling::Publish

on:
  workflow_dispatch:
    inputs:
      IROHA2_IMAGE_TAG:
        required: true
        default: stable
      IROHA2_IMAGE_RELEASE:
        required: true
      IROHA2_DOCKERFILE:
        required: true
        default: Dockerfile.glibc
      IROHA2_PROFILE:
        required: true
        default: profiling
      IROHA2_RUSTFLAGS:
        required: false
        default: -C force-frame-pointers=on --cfg wasm_profiling

jobs:
  registry:
    runs-on: [self-hosted, Linux, iroha2-dev-push]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Soramitsu Harbor
        uses: docker/login-action@v3
        with:
          registry: docker.soramitsu.co.jp
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        if: always()
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      - name: Build and push iroha2:profiling-image
        uses: docker/build-push-action@v5
        if: always()
        with:
          push: true
          tags: |
            hyperledger/iroha2:${{ github.event.inputs.IROHA2_IMAGE_TAG }}-${{ github.event.inputs.IROHA2_IMAGE_RELEASE }}-profiling
            docker.soramitsu.co.jp/iroha2/iroha2:${{ github.event.inputs.IROHA2_IMAGE_TAG }}-${{ github.event.inputs.IROHA2_IMAGE_RELEASE }}-profiling
          labels: commit=${{ github.sha }}
          build-args: |
            "PROFILE=${{ github.event.inputs.IROHA2_PROFILE }}"
            "RUSTFLAGS=${{ github.event.inputs.IROHA2_RUSTFLAGS }}"
          file: ${{ github.event.inputs.IROHA2_DOCKERFILE }}
          # This context specification is required
          context: .
