name: I2::Dev::Nightly::Publish

on: workflow_dispatch

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    container:
      image: hyperledger/iroha2-ci:nightly-2024-01-12
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push iroha2:dev-nightly image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: hyperledger/iroha2:dev-nightly-${{ github.sha }}
          labels: commit=${{ github.sha }}
          build-args: TAG=dev
          # This context specification is required
          context: .
